// goa-data.js — Hindu Temples of Goa
// Coordinates sourced from Wikipedia / Google Maps where available; null where unverified.
// Timings compiled from official temple sites and tourism sources (2024-25).

const TEMPLES_GOA = [
  {
    id: 1,
    name: "Shri Mangueshi Temple (Mangueshi Devasthan)",
    deity: "Lord Manguesh (Shiva)",
    district: "North Goa",
    location: "Mangeshi Village, Priol, Ponda Taluka, Goa 403401",
    lat: 15.4102, lng: 73.9617,
    timing: "6:00 AM – 10:00 PM (daily); Darshan break: 12:00–1:00 PM",
    phone: "",
    description: "One of the largest and wealthiest temples in Goa, dedicated to Lord Manguesh — a Goan manifestation of Shiva. The deity was relocated from Kushasthali (Cortalim) in 1560 AD when the Portuguese began destroying temples in Salsette. The iconic seven-storey octagonal Deepastambha (lamp tower) is the highlight, especially when illuminated at night. The complex includes shrines to Parvati, Ganesha, Nandi, Virabhadra, Shantadurga, and Lakshmi Narayan. Kuldeva of Gaud Saraswat Brahmins. Major festivals: Magh Purnima Jatrotsav, Ram Navami, Navaratri, Mahashivaratri. Managed by a private temple trust; live darshan available online.",
    famous: true,
    tags: ["shiva","gaud saraswat","ponda","deepastambha","kuldeva","major"],
    dressCode: "Modest attire required. Women must cover legs (full-length saree, churidar, or skirt). Men in dhoti or trousers. No shorts or revealing clothes.",
    photography: "Permitted in outer courtyard and grounds. Not allowed inside the sanctum.",
    nearestBus: "Mardol/Priol bus stop on Panaji–Ponda NH-4A; KTC buses from Panaji Kadamba Bus Stand (21 km)",
    nearestRail: "Karmali Railway Station (Old Goa), Konkan Railway — approx. 15 km"
  },
  {
    id: 2,
    name: "Shri Shantadurga Temple (Shantadurga Saunsthan)",
    deity: "Goddess Shantadurga (Santeri)",
    district: "North Goa",
    location: "Kapileswari - Kavlem Rd, Donshiwado, Kavlem Village, Ponda Taluka, Goa 403401",
    lat: 15.3894, lng: 74.0025,
    timing: "5:30 AM – 12:30 PM and 1:30 PM – 8:30 PM (daily)",
    phone: "0832-2420779 / 0832-2427972 / 0832-2436666",
    description: "One of the largest temple complexes in Goa, dedicated to Goddess Shantadurga — the mediator between Vishnu and Shiva — who is Kuldevi of many Gaud Saraswat Brahmin families. Originally at Quelossim (Keloshi) in Salcete, destroyed by the Portuguese in 1566; rebuilt at Kavlem between 1730–1738 AD under Maratha patronage. The white marble idol of Shantadurga holds two serpents representing Vishnu and Shiva. The temple blends Saraswat and Roman architectural styles with a prominent shikhara and deepastambha. Lodging (agrashalas) available for pilgrims. Major festivals: Jatra Utsav, Vasant Utsav, Mahashivratri, Ram Navami, Navaratri, Dussehra. Live darshan on official website.",
    famous: true,
    tags: ["durga","devi","gaud saraswat","ponda","kuldevi","major"],
    dressCode: "Traditional modest dress required. Saree or churidar for women; dhoti or trousers for men. No Western casuals in inner sanctum.",
    photography: "Not allowed inside the temple.",
    nearestBus: "Ponda KTC Bus Stand (4 km); buses from Panaji and Margao to Ponda",
    nearestRail: "Madgaon (Margao) Railway Station — approx. 21 km"
  },
  {
    id: 3,
    name: "Shri Mahalasa Narayani Temple",
    deity: "Goddess Mahalasa (Mohini avatar of Vishnu)",
    district: "North Goa",
    location: "Shri Mahalasa Saunsthan, Mardol, Ponda Taluka, Goa 403404",
    lat: 15.4133, lng: 73.9610,
    timing: "6:30 AM – 8:30 PM (daily); Aarti: 12:30 PM and 8:30 PM",
    phone: "+91-832-2343421 / 832-2343883",
    description: "A 450+ year old temple dedicated to Goddess Mahalasa (Mahalsa), worshipped as the Mohini avatar of Vishnu and Kuldevi of several Kshatriya, Brahmin and Bhandari communities. The original temple was at Verna (Salcete) and was destroyed by the Portuguese; the idol was rescued and consecrated at Mardol in the 17th century. Famous for its enormous brass bell (said to punish those who lie while ringing it), a massive 12.5-metre brass Deepastambha, and fine wood carvings. Sundays are the Goddess's special day — a grand Palkhi (palanquin) procession is held weekly. Major festivals: Mahalasa Pindikotsava, Navaratrotsava, Magha Jatra. Located 1 km from Mangueshi Temple.",
    famous: true,
    tags: ["vishnu","mohini","mahalasa","ponda","mardol","gaud saraswat","major"],
    dressCode: "Western clothing and revealing attire strictly prohibited. Traditional dress preferred.",
    photography: "",
    nearestBus: "Mardol bus stop on NH-4A Panaji–Ponda highway; state and private buses from Panaji (21 km) and Ponda (9 km)",
    nearestRail: "Karmali Railway Station (Old Goa), Konkan Railway — approx. 14 km"
  },
  {
    id: 4,
    name: "Shri Nagueshi Temple (Nagesh Temple)",
    deity: "Lord Naguesh (Shiva)",
    district: "North Goa",
    location: "Bandode Village, Ponda Taluka, Goa 403401",
    lat: 15.3986, lng: 74.0114,
    timing: "6:00 AM – 10:00 PM (daily)",
    phone: "",
    description: "One of the oldest temples in Goa, notable for never having been demolished or rebuilt — only renovated. The Sabha Mandap contains exquisite wood carvings depicting scenes from the Ramayana on one side and images of Ashtadikpalas (eight directional guardians) and Gandharvas on the other. Stone inscriptions of old scriptures are another highlight. The temple has a large sacred tank and a lamp tower. Located 4 km east of Ponda town.",
    famous: true,
    tags: ["shiva","ponda","ancient","wood carvings","major"],
    dressCode: "",
    photography: "",
    nearestBus: "Bandode/Ponda local bus services; Ponda KTC Bus Stand is 4 km",
    nearestRail: "Madgaon (Margao) Railway Station — approx. 24 km"
  },
  {
    id: 5,
    name: "Shri Ramnathi Temple (Ramnath Devasthan)",
    deity: "Lord Ramnath (Shiva) with Panchayatan deities",
    district: "North Goa",
    location: "Shree Ramnath Mandir, Ramnathim, Bandivade, Ponda Taluka, Goa 403401",
    lat: 15.3820, lng: 73.9987,
    timing: "7:30 AM – 9:30 PM (daily)",
    phone: "",
    description: "A 450-year-old temple of great religious importance to Gaud Saraswat Brahmins, following the system of Panchayatan — housing five principal deities: Shri Ramanath (chief deity/Shiva), Shanteri (Shantadurga), Kamakshi, Lakshmi Narayan, and Ganapati, with Betal and Kalbhairav also present. The temple was relocated from Salcete in the 16th century to protect it from Portuguese destruction. Traditional Goan temple architecture with fine carvings.",
    famous: true,
    tags: ["shiva","panchayatan","gaud saraswat","ponda","major"],
    dressCode: "",
    photography: "",
    nearestBus: "Local buses from Ponda to Bandivade; Ponda KTC Bus Stand approx. 5 km",
    nearestRail: "Madgaon (Margao) Railway Station — approx. 22 km"
  },
  {
    id: 6,
    name: "Shri Kamakshi Temple",
    deity: "Goddess Kamakshi (Parvati / Kamakhya form)",
    district: "North Goa",
    location: "Shiroda Village, Ponda Taluka, Goa 403103",
    lat: 15.3657, lng: 74.0330,
    timing: "5:30 AM – 8:30 PM (daily)",
    phone: "",
    description: "A strict orthodox Hindu temple built in the late 16th century, originally located in Raia village, Salcete. The idol of Goddess Kamakshi was smuggled across the river by a potter from Raia to save it from the Portuguese Inquisition, and was eventually installed at Shiroda (Thal ward) in Ponda Taluka. The deity is a form of Goddess Parvati linked with Tantric traditions, worshipped also as Kamakhya. The temple complex features a large Sabha Mandap, water tank, and shrines to Shiva, Lakshmi Narayan, and Shantadurga. Major festivals: Navratri, Dussehra, Jatra.",
    famous: true,
    tags: ["devi","parvati","kamakhya","tantric","ponda","major"],
    dressCode: "Orthodox temple — strictly traditional dress. Covering required for both men and women.",
    photography: "",
    nearestBus: "Local buses from Ponda to Shiroda; Ponda KTC Bus Stand approx. 8 km",
    nearestRail: "Madgaon (Margao) Railway Station — approx. 19 km"
  },
  {
    id: 7,
    name: "Shri Saptakoteshwar Temple",
    deity: "Lord Saptakoteshwar (Shiva)",
    district: "North Goa",
    location: "Narve Village, Bicholim Taluka, Goa",
    lat: 15.5792, lng: 73.9719,
    timing: "6:00 AM – 7:00 PM (daily)",
    phone: "",
    description: "One of the six great Shiva shrines of the Konkan region and former patron deity of the Kadamba kings. Originally built around the 13th–14th century, the temple was demolished by the Portuguese and the idol hidden; it was rebuilt at Narve in Bicholim by the Maratha ruler Chhatrapati Shivaji Maharaj. The temple pond, the architectural mandap blending Mughal and European elements, and the tall lamp tower are notable features. The Peshwas also made significant contributions to the temple.",
    famous: true,
    tags: ["shiva","kadamba","maratha","bicholim","major","konkan"],
    dressCode: "",
    photography: "",
    nearestBus: "Bus services from Mapusa and Panaji to Bicholim/Narve; Narve bus stop",
    nearestRail: "Thivim Railway Station, Konkan Railway — approx. 15 km"
  },
  {
    id: 8,
    name: "Mahadev Temple, Tambdi Surla",
    deity: "Lord Mahadev (Shiva)",
    district: "South Goa",
    location: "Tambdi Surla Village, near Bhagwan Mahaveer Wildlife Sanctuary, Sanguem Taluka, Goa 403406",
    lat: 15.4389, lng: 74.2522,
    timing: "8:30 AM – 5:30 PM (daily)",
    phone: "",
    description: "The oldest surviving temple in Goa, dating to the 12th century and built during the Kadamba-Yadava dynasty period. Protected monument maintained by the Archaeological Survey of India. Built entirely of black basalt brought from the Deccan Plateau, assembled without mortar. The temple survived Portuguese destruction because of its remote forest location deep within what is now the Bhagwan Mahaveer Wildlife Sanctuary. Features a Garbhagriha, Antarala, and Nandi Mandapa with four pillars carved with elephants and chains. The stone ceiling bears a lotus rosette carving; bas-reliefs of Shiva, Vishnu and Brahma with consorts line the walls. Local legend says a king cobra resides in the sanctum at night.",
    famous: true,
    tags: ["shiva","kadamba","12th century","ASI","ancient","forest","south goa","major"],
    dressCode: "Modest attire required as a mark of respect.",
    photography: "Permitted — the temple is an ASI protected monument.",
    nearestBus: "Very limited bus services; nearest town Molem (~13 km). Private vehicle or taxi recommended.",
    nearestRail: "Kulem Railway Station — approx. 21 km"
  },
  {
    id: 9,
    name: "Shri Damodar Temple",
    deity: "Lord Damodar (Shiva)",
    district: "South Goa",
    location: "Zambaulim Village, Quepem Taluka, Goa 403705",
    lat: 15.1660, lng: 74.1010,
    timing: "6:00 AM – 8:30 PM (daily)",
    phone: "",
    description: "A beautifully situated temple on the banks of the Kushavati River at Zambaulim, dedicated to Lord Damodar — a form of Shiva. Known for its striking architecture and lively celebrations of Shigmo (Goan Holi), Mahashivratri, and Kartik Poornima. The riverside setting makes it one of the most scenic temple locations in Goa.",
    famous: true,
    tags: ["shiva","south goa","quepem","riverside","major"],
    dressCode: "",
    photography: "",
    nearestBus: "Bus services from Margao to Quepem; Zambaulim local buses",
    nearestRail: "Madgaon (Margao) Railway Station — approx. 28 km"
  },
  {
    id: 10,
    name: "Shri Lairai Devi Temple",
    deity: "Goddess Lairai Devi (Parvati)",
    district: "North Goa",
    location: "Shirgao Village, Bicholim Taluka, Goa",
    lat: 15.6102, lng: 73.9511,
    timing: "6:00 AM – 8:00 PM (daily); all night during Jatra",
    phone: "",
    description: "One of the oldest and most famous devasthans in Goa, located at Shirgao in Bicholim Taluka. Goddess Lairai, an incarnation of Parvati, is revered across Goa; interestingly, Goan Hindus and Catholics recognise Lairai Devi and the Virgin Mary of nearby Mapusa as sisters. The temple is celebrated for the annual Lairai Dhondachi Zatra (held in April/May), one of Goa's most spectacular festivals, where approximately 20,000 devotees ('dhonds') — men and women — walk barefoot across a bed of burning hot coals (homkhand) in an act of devotion, carrying blazing torches through the night. The festival also features spirited dancing, chanting, and a massive bonfire.",
    famous: true,
    tags: ["devi","parvati","bicholim","firewalking","jatra","ancient","major"],
    dressCode: "",
    photography: "Permitted outside sanctum; be respectful during rituals.",
    nearestBus: "Bus services from Mapusa to Bicholim/Shirgao; Mapusa Bus Stand approx. 13 km",
    nearestRail: "Thivim Railway Station, Konkan Railway — approx. 18 km"
  },
  {
    id: 11,
    name: "Shri Bhagavati Temple, Parshem",
    deity: "Goddess Bhagavati (Lakshmi form)",
    district: "North Goa",
    location: "Parshem Village, Pernem Taluka, Goa 403512",
    lat: 15.7188, lng: 73.8042,
    timing: "",
    phone: "",
    description: "One of the oldest temples in Goa (~500 years), dedicated to Goddess Bhagavati, a form of Goddess Lakshmi. The complex comprises five temples housing Shri Bhagavati, Shri Sateri, Shri Dev Ravalnath, Shri Dev Bhivangi Panchakshari, and Brahma/Vishnu/Ganesh/Shankar shrines. Famous for two five-storey lamp towers. Attracts over 20,000 visitors during Dussehra and the annual Jatra festival.",
    famous: true,
    tags: ["bhagavati","lakshmi","pernem","dussehra","north goa","major"],
    dressCode: "",
    photography: "",
    nearestBus: "Bus services from Mapusa to Pernem/Parshem; Pernem Bus Stand",
    nearestRail: "Thivim Railway Station, Konkan Railway — approx. 30 km"
  },
  {
    id: 12,
    name: "Shri Mahalaxmi Temple, Bandora",
    deity: "Goddess Mahalakshmi",
    district: "North Goa",
    location: "Shree Mahalaxmi Sausthan Bandiwade, Bandora, Ponda Taluka, Goa 403401",
    lat: 15.4016, lng: 73.9887,
    timing: "",
    phone: "",
    description: "Dedicated to Goddess Mahalakshmi, this temple has a unique iconographic feature — a Shiva Linga on the head of the deity, reflecting a fusion of Shaiva and Vaishnava traditions. The deity was originally worshipped by the Silahara and Kadamba rulers. The present shrine was established in 1866 after the original was destroyed by the Portuguese, and is a fine example of traditional Konkani temple architecture.",
    famous: true,
    tags: ["lakshmi","ponda","bandora","silahara","kadamba","major"],
    dressCode: "",
    photography: "",
    nearestBus: "Local buses from Ponda; Ponda KTC Bus Stand approx. 3 km",
    nearestRail: "Madgaon (Margao) Railway Station — approx. 23 km"
  },
  {
    id: 13,
    name: "Shri Mallikarjun Temple",
    deity: "Lord Mallikarjun (Shiva)",
    district: "South Goa",
    location: "Shristhal Village, Canacona Taluka, South Goa",
    lat: 14.9868, lng: 74.1032,
    timing: "",
    phone: "",
    description: "A 16th-century temple refurbished in 1778, dedicated to Lord Mallikarjun, an incarnation of Shiva. According to legend, it was built on the spot where Shiva and Parvati reunited after a long separation. Notable for carved wooden pillars depicting scenes from the Puranas and Mahabharata, carved doorkeeper (dwarpal) silhouettes, and colourful murals. An excellent example of Kshatriya ancestral architecture. Located in Shristhal village in Canacona, the southernmost taluka of Goa.",
    famous: true,
    tags: ["shiva","canacona","south goa","wood carvings","16th century"],
    dressCode: "",
    photography: "",
    nearestBus: "Bus services from Margao to Canacona/Chaudi; Chaudi Bus Stand approx. 12 km",
    nearestRail: "Canacona Railway Station — approx. 12 km"
  },
  {
    id: 14,
    name: "Shri Chandranath Temple (Chandreshwar Bhuthnath)",
    deity: "Lord Chandreshwar (Shiva / Chandranath)",
    district: "South Goa",
    location: "Chandranath Hill, Paroda, Quepem Taluka, South Goa",
    lat: 15.2300, lng: 74.0880,
    timing: "",
    phone: "",
    description: "A revered hilltop temple in South Goa dedicated to Lord Chandreshwar (Shiva in his lunar aspect, also called Bhuthnath). The temple is known for its ancient chariot with exquisite woodcarvings, one of the finest in Goa. The elevated location on Chandranath Hill offers panoramic views. The Shivalinga here is said to glow in moonlight on full moon nights.",
    famous: true,
    tags: ["shiva","south goa","quepem","hilltop","ancient chariot"],
    dressCode: "",
    photography: "",
    nearestBus: "Bus services from Margao to Quepem; local transport to Paroda",
    nearestRail: "Madgaon (Margao) Railway Station — approx. 22 km"
  },
  {
    id: 15,
    name: "Shri Vijayadurga Temple, Kerim",
    deity: "Goddess Vijayadurga (Durga)",
    district: "North Goa",
    location: "Kerim Village, Ponda Taluka, Goa",
    lat: 15.4230, lng: 74.0290,
    timing: "",
    phone: "",
    description: "Originally located at Sancoale alongside Shantadurga and Lakshminarsimha temples, the Vijayadurga deity was shifted to Kerim in Ponda Taluka following the Portuguese Inquisition and the destruction of temples in Sancoale. Goddess Vijayadurga ('Victorious Durga') is venerated as the deity who intervened in the battle between Shiva and Vishnu, and later destroyed demons harassing Brahmins at Sancoale, earning the title Vijaya.",
    famous: false,
    tags: ["durga","devi","ponda","relocated","portuguese"],
    dressCode: "",
    photography: "",
    nearestBus: "Local buses from Ponda to Kerim area",
    nearestRail: "Madgaon (Margao) Railway Station — approx. 26 km"
  },
  {
    id: 16,
    name: "Shri Brahma Karmali Temple",
    deity: "Lord Brahma",
    district: "North Goa",
    location: "Carambolim Village, Sattari Taluka, Goa",
    lat: 15.5650, lng: 74.0950,
    timing: "",
    phone: "",
    description: "One of the very few temples in India dedicated to Lord Brahma (the creator deity), making it a unique pilgrimage site since Pushkar in Rajasthan is popularly believed to be the only Brahma temple. The intricately crafted idol in the sanctum — depicting Brahma with Shiva and Vishnu — is dated to the 12th century. The temple served as an important centre of the freedom struggle during the Goa Liberation movement. Dating to the 12th century, the serene location and simple architecture attract devotees and history enthusiasts alike.",
    famous: true,
    tags: ["brahma","sattari","12th century","rare","freedom struggle","north goa"],
    dressCode: "",
    photography: "",
    nearestBus: "Limited bus services; Valpoi Bus Stand approx. 7 km",
    nearestRail: "Thivim Railway Station — approx. 40 km"
  },
  {
    id: 17,
    name: "Shri Mahadeo Temple, Surla (Sri Mahadeva Bhumika / Tambdi Surla ancillary)",
    deity: "Lord Mahadev (Shiva)",
    district: "North Goa",
    location: "Sal Village, Bicholim Taluka, Goa",
    lat: null, lng: null,
    timing: "",
    phone: "",
    description: "A large Shiva temple accessible from Sal in Bicholim Taluka (25 km from Mapusa). Set amid naturally beautiful surroundings, the temple is popular for its three-day festival of 'Gades' beginning on Phalgun Purnima, when thousands of pilgrims visit. Also known as Shri Mahadeo Bhumika.",
    famous: false,
    tags: ["shiva","bicholim","north goa","gades festival"],
    dressCode: "",
    photography: "",
    nearestBus: "Bus services from Mapusa to Bicholim; local services to Sal",
    nearestRail: "Thivim Railway Station, Konkan Railway — approx. 20 km"
  },
  {
    id: 18,
    name: "Shri Laxmi Narayan Temple, Veling",
    deity: "Goddess Lakshmi and Lord Vishnu (Narayana)",
    district: "North Goa",
    location: "Veling Village, Ponda Taluka, Goa",
    lat: 15.4053, lng: 74.0151,
    timing: "",
    phone: "",
    description: "An 18th-century shrine dedicated to Goddess Lakshmi and Lord Vishnu. The idol was relocated from Salcete in the late 16th century when the Portuguese captured Goa. The temple complex features fine wooden carvings, traditional paintings, a sacred water tank, and a musicians' gallery (navatkhana), reflecting the characteristic Goan Hindu temple style.",
    famous: false,
    tags: ["vishnu","lakshmi","ponda","18th century","gsa"],
    dressCode: "",
    photography: "",
    nearestBus: "Local buses from Ponda to Veling; Ponda KTC Bus Stand approx. 6 km",
    nearestRail: "Madgaon (Margao) Railway Station — approx. 22 km"
  },
  {
    id: 19,
    name: "Shri Devaki Krishna Devasthan",
    deity: "Goddess Devaki and Lord Krishna",
    district: "North Goa",
    location: "Marcel (Mashel) Village, Ponda Taluka, Goa",
    lat: 15.4560, lng: 73.9840,
    timing: "",
    phone: "",
    description: "A unique temple dedicated jointly to Goddess Devaki (Krishna's mother) and Lord Krishna — a rare combination in Indian temples. Located at Marcel (Mashel) in Ponda Taluka, this is a significant temple in the Goan GSB religious tradition. Features traditional Goan temple architecture.",
    famous: false,
    tags: ["krishna","devaki","vishnu","ponda","rare","gsa"],
    dressCode: "",
    photography: "",
    nearestBus: "Local buses from Panaji or Ponda to Marcel; Panaji approx. 15 km",
    nearestRail: "Karmali Railway Station (Old Goa) — approx. 10 km"
  },
  {
    id: 20,
    name: "Shri Shantadurga Kunkalikarin Temple, Fatorpa",
    deity: "Goddess Shantadurga (Kunkalikarin form)",
    district: "South Goa",
    location: "Fatorpa, Quepem Taluka, South Goa",
    lat: 15.1950, lng: 74.0600,
    timing: "",
    phone: "",
    description: "One of the three principal Shantadurga temples in Goa (the others at Kavlem and Dhargal/Pemem). The deity is worshipped in the Kunkalikarin form of Shantadurga. The annual Zatra (Jatra Utsav) of the goddess is an important festival drawing large crowds from South Goa.",
    famous: false,
    tags: ["durga","shantadurga","south goa","quepem","zatra"],
    dressCode: "",
    photography: "",
    nearestBus: "Buses from Margao to Quepem; local services to Fatorpa",
    nearestRail: "Madgaon (Margao) Railway Station — approx. 22 km"
  },
];

// Export for use in app
if (typeof module !== 'undefined' && module.exports) {
  module.exports = goaTemples;
}
