// KeralaDevasthanam — Temple Data (extended)
// Fields: id, name, deity, district, location, lat, lng,
//         timing, phone, description, famous, tags,
//         dressCode, photography, nearestBus, nearestRail

const TEMPLES_KERALA = [
  {
    id: 1,
    name: "Sree Padmanabhaswamy Temple",
    deity: "Lord Vishnu",
    district: "Thiruvananthapuram",
    location: "East Fort, Thiruvananthapuram",
    lat: 8.4826, lng: 76.9488,
    timing: "3:30 AM – 12:00 PM, 5:00 PM – 7:15 PM",
    phone: "+91-471-2450233",
    description: "One of the wealthiest temples in the world. The presiding deity Lord Padmanabha is seen in the Ananthshayana posture on the serpent Adi Shesha. Only Hindus are permitted to enter.",
    famous: true,
    tags: ["famous", "vishnu", "heritage"],
    dressCode: "Men: Dhoti (mundu) only — no shirts, no pants inside. Women: Saree or half-saree (set mundu). Western clothing strictly not allowed.",
    photography: "Strictly prohibited inside the temple premises. No cameras or mobile phones allowed.",
    nearestBus: "East Fort Bus Stand (0.1 km)",
    nearestRail: "Thiruvananthapuram Central Railway Station (1.2 km)"
  },
  {
    id: 2,
    name: "Guruvayur Sree Krishna Temple",
    deity: "Lord Krishna",
    district: "Thrissur",
    location: "Guruvayur, Thrissur",
    lat: 10.5943, lng: 76.0418,
    timing: "3:00 AM – 1:00 PM, 4:30 PM – 9:15 PM",
    phone: "+91-487-2556335",
    description: "Known as the Dwarka of the South. One of the most important places of worship for Hindus in Kerala. The idol is made of Patala Anjana stone.",
    famous: true,
    tags: ["famous", "krishna", "heritage"],
    dressCode: "Men: Dhoti only — no shirts inside sanctum. Women: Saree or churidar with dupatta. No jeans or shorts.",
    photography: "Not permitted inside the temple. Photography allowed in outer courtyard.",
    nearestBus: "Guruvayur Bus Stand (0.3 km)",
    nearestRail: "Guruvayur Railway Station (0.5 km) · Thrissur Railway Station (29 km)"
  },
  {
    id: 3,
    name: "Sabarimala Sree Dharmasastha Temple",
    deity: "Lord Ayyappa",
    district: "Pathanamthitta",
    location: "Sabarimala, Pathanamthitta",
    lat: 9.4341, lng: 77.0839,
    timing: "Seasonal: Nov–Jan (Mandalam & Makaravilakku) and Vishu season",
    phone: "+91-4735-202555",
    description: "Most visited pilgrimage site in Kerala, situated on a hill at 914 m. Famous for the Makaravilakku festival. Pilgrims must observe 41-day Vratha before visiting.",
    famous: true,
    tags: ["famous", "ayyappa", "pilgrimage"],
    dressCode: "All pilgrims must wear black or blue clothing (Irumudi). Casual clothing not permitted. Pilgrim's Irumudi (sacred bundle) is mandatory.",
    photography: "Photography permitted in outer areas. Strictly prohibited in sanctum sanctorum and during rituals.",
    nearestBus: "Nilackal / Pampa base camp — shuttle buses available from all Kerala districts",
    nearestRail: "Chengannur Railway Station (67 km) · Kottayam Railway Station (78 km)"
  },
  {
    id: 4,
    name: "Attukal Bhagavathy Temple",
    deity: "Goddess Bhagavathi",
    district: "Thiruvananthapuram",
    location: "Attukal, Thiruvananthapuram",
    lat: 8.4937, lng: 76.9522,
    timing: "4:30 AM – 12:30 PM, 5:00 PM – 8:30 PM",
    phone: "+91-471-2352434",
    description: "Known as the Sabarimala of Women. Holds the Guinness World Record for the largest gathering of women for a religious event — Attukal Pongala, with over 3 million women participating.",
    famous: true,
    tags: ["famous", "bhagavathi", "women"],
    dressCode: "Women: Saree or churidar. Men: Dhoti or trousers with shirt. Modest clothing expected.",
    photography: "Photography allowed in outer premises. Not permitted during rituals or inside sanctum.",
    nearestBus: "Attukal Bus Stop (0.1 km) · Thiruvananthapuram City Bus Terminal (2 km)",
    nearestRail: "Thiruvananthapuram Central Railway Station (2.5 km)"
  },
  {
    id: 5,
    name: "Vadakkunnathan Temple",
    deity: "Lord Shiva",
    district: "Thrissur",
    location: "Thrissur Town",
    lat: 10.5229, lng: 76.2157,
    timing: "4:00 AM – 10:30 AM, 5:00 PM – 8:30 PM",
    phone: "+91-487-2422682",
    description: "Ancient Shiva temple at the heart of Thrissur. Famous for Thrissur Pooram, the grandest temple festival in Kerala. UNESCO-recognized intangible cultural heritage.",
    famous: true,
    tags: ["famous", "shiva", "heritage"],
    dressCode: "Men: Dhoti only. Women: Saree. Western clothing not allowed inside. Footwear removed at entrance.",
    photography: "Not permitted inside the temple. Permitted in the surrounding thekkinkadu maidan during Pooram.",
    nearestBus: "Thrissur KSRTC Bus Stand (0.8 km) · Round South Bus Stop (0.2 km)",
    nearestRail: "Thrissur Railway Station (1.5 km)"
  },
  {
    id: 6,
    name: "Ernakulathappan Temple",
    deity: "Lord Shiva",
    district: "Ernakulam",
    location: "Durbar Hall Ground, Ernakulam",
    lat: 9.9816, lng: 76.2883,
    timing: "4:00 AM – 11:00 AM, 5:00 PM – 8:30 PM",
    phone: "+91-484-2353366",
    description: "The presiding deity of Ernakulam city. Famous for the grand Ernakulam Shiva Ratri Mahotsavam, celebrated over 8 days with lakhs of devotees.",
    famous: true,
    tags: ["shiva", "famous"],
    dressCode: "Men: Dhoti preferred; clean trousers acceptable. Women: Saree or churidar with dupatta.",
    photography: "Permitted in outer courtyard. Restricted inside sanctum.",
    nearestBus: "Ernakulam South Bus Stand (1 km) · High Court Junction Bus Stop (0.4 km)",
    nearestRail: "Ernakulam South Railway Station (1.2 km)"
  },
  {
    id: 7,
    name: "Ettumanoor Mahadeva Temple",
    deity: "Lord Shiva",
    district: "Kottayam",
    location: "Ettumanoor, Kottayam",
    lat: 9.6697, lng: 76.5570,
    timing: "3:30 AM – 12:00 PM, 5:00 PM – 8:30 PM",
    phone: "+91-481-2531234",
    description: "Famous Shiva temple known for the richly decorated golden flagmast and Ezharaponnana (seven and a half golden elephants). The temple murals are among the finest in Kerala.",
    famous: true,
    tags: ["shiva", "famous"],
    dressCode: "Men: Dhoti or mundu — no shirts inside. Women: Saree or half-saree. No jeans, shorts, or sleeveless tops.",
    photography: "Strictly prohibited inside. Murals and outer architecture may be photographed.",
    nearestBus: "Ettumanoor Bus Stand (0.2 km)",
    nearestRail: "Kottayam Railway Station (12 km)"
  },
  {
    id: 8,
    name: "Ambalapuzha Sree Krishna Temple",
    deity: "Lord Krishna",
    district: "Alappuzha",
    location: "Ambalapuzha, Alappuzha",
    lat: 9.3851, lng: 76.3440,
    timing: "5:30 AM – 12:00 PM, 5:30 PM – 8:30 PM",
    phone: "+91-477-2272500",
    description: "Famous for Ambalapuzha Palpayasam — rice pudding offered to the deity daily. Legend says Lord Krishna played a chess game here and the offering continues as fulfillment of that promise.",
    famous: true,
    tags: ["krishna", "famous"],
    dressCode: "Men: Dhoti/mundu — shirts removed at sanctum. Women: Saree or half-saree. Modest attire required.",
    photography: "Not permitted inside the temple.",
    nearestBus: "Ambalapuzha Bus Stand (0.3 km)",
    nearestRail: "Alappuzha Railway Station (14 km)"
  },
  {
    id: 9,
    name: "Mannarasala Sree Nagaraja Temple",
    deity: "Lord Nagaraja",
    district: "Alappuzha",
    location: "Haripad, Alappuzha",
    lat: 9.2644, lng: 76.4517,
    timing: "6:30 AM – 1:00 PM, 5:00 PM – 7:30 PM",
    phone: "+91-479-2412233",
    description: "Ancient serpent deity temple in a dense forest grove of 16 acres. Managed by a woman (Amma). Famous for the Ayilya festival and thousands of snake idols in the grove.",
    famous: true,
    tags: ["nagaraja", "famous"],
    dressCode: "Men: Mundu/dhoti. Women: Saree or half-saree. No leather items (belts, wallets) inside premises.",
    photography: "Permitted in the forest grove. Restricted near sanctum and snake-idol areas.",
    nearestBus: "Haripad Bus Stand (3 km)",
    nearestRail: "Haripad Railway Station (3.5 km)"
  },
  {
    id: 10,
    name: "Aranmula Parthasarathy Temple",
    deity: "Lord Vishnu",
    district: "Pathanamthitta",
    location: "Aranmula, Pathanamthitta",
    lat: 9.3518, lng: 76.6166,
    timing: "5:30 AM – 12:00 PM, 5:00 PM – 8:00 PM",
    phone: "+91-468-2312234",
    description: "Famous for the Aranmula Uthrittathi Vallamsankedam — a snake boat race held as a religious offering. One of the 108 Divya Desams of Lord Vishnu.",
    famous: true,
    tags: ["vishnu", "famous"],
    dressCode: "Men: Dhoti mandatory — shirts not allowed in sanctum. Women: Saree or set mundu.",
    photography: "Not allowed inside. Boat race festival photography is permitted.",
    nearestBus: "Aranmula Bus Stand (0.5 km) · Chengannur Bus Stand (11 km)",
    nearestRail: "Chengannur Railway Station (11 km)"
  },
  {
    id: 11,
    name: "Thirunelli Temple",
    deity: "Lord Vishnu",
    district: "Wayanad",
    location: "Brahmagiri, Wayanad",
    lat: 11.9285, lng: 76.0698,
    timing: "6:00 AM – 1:00 PM, 5:00 PM – 7:30 PM",
    phone: "+91-4936-260502",
    description: "Ancient Vishnu temple deep in the Brahmagiri hills at 900 m elevation. Called 'Kashi of the South'. One of the holiest spots for performing ancestral rites (pitru tharpanam).",
    famous: true,
    tags: ["vishnu", "famous", "heritage"],
    dressCode: "Men: Dhoti only inside sanctum. Women: Saree. Smart casual acceptable in outer areas.",
    photography: "Allowed in temple surroundings and forest. Not permitted inside sanctum.",
    nearestBus: "Mananthavady Bus Stand (32 km) · Kalpetta Bus Stand (50 km)",
    nearestRail: "Kozhikode Railway Station (104 km) · Mysuru Railway Station (96 km)"
  },
  {
    id: 12,
    name: "Kottiyoor Mahadeva Temple",
    deity: "Lord Shiva",
    district: "Kannur",
    location: "Kottiyoor, Kannur",
    lat: 11.9774, lng: 75.9045,
    timing: "Seasonal: May–June (Vaisakha Mahotsavam only)",
    phone: "+91-490-2345678",
    description: "Remote forest temple on the banks of the Bavali River. Accessible only during the Vaisakha Mahotsavam season (28 days). No idol — Lord is worshipped as a naturally formed Shivalingam.",
    famous: true,
    tags: ["shiva", "forest", "famous"],
    dressCode: "Men: Dhoti only — no shirts. Women: Saree or half-saree. Pilgrim dress code strictly enforced.",
    photography: "Photography not permitted at the main shrine. Forest areas may be photographed.",
    nearestBus: "Kottiyoor Bus Stand (1 km) · Thalassery Bus Stand (52 km)",
    nearestRail: "Thalassery Railway Station (52 km) · Kannur Railway Station (60 km)"
  },
  {
    id: 13,
    name: "Chettikulangara Bhagavathy Temple",
    deity: "Goddess Bhagavathi",
    district: "Kollam",
    location: "Chettikulangara, Kollam",
    lat: 9.1558, lng: 76.5856,
    timing: "4:30 AM – 12:00 PM, 5:00 PM – 8:00 PM",
    phone: "+91-474-2557234",
    description: "Powerful Bhagavathi temple. The Chettikulangara Bharani is among the grandest festivals in South Kerala, famous for the illuminated kuthira (horse) procession.",
    famous: true,
    tags: ["bhagavathi", "famous"],
    dressCode: "Men: Dhoti or trousers with shirt. Women: Saree or churidar. Modest dress mandatory.",
    photography: "Allowed in outer precincts. Not allowed near sanctum.",
    nearestBus: "Chettikulangara Bus Stop (0.2 km) · Kollam KSRTC Bus Stand (8 km)",
    nearestRail: "Kollam Railway Station (8 km)"
  },
  {
    id: 14,
    name: "Pazhavangadi Ganapathy Temple",
    deity: "Lord Ganesha",
    district: "Thiruvananthapuram",
    location: "East Fort, Thiruvananthapuram",
    lat: 8.4841, lng: 76.9491,
    timing: "4:00 AM – 9:30 PM (open all day)",
    phone: "+91-471-2461234",
    description: "Famous Ganapathy temple adjacent to Padmanabhaswamy Temple. Known for the unique custom of offering coconuts. One of the most visited Ganesha temples in Kerala.",
    famous: true,
    tags: ["ganesha", "famous"],
    dressCode: "Men: Dhoti preferred; clean formal wear acceptable. Women: Saree or churidar with dupatta.",
    photography: "Allowed in outer areas. Not permitted inside sanctum.",
    nearestBus: "East Fort Bus Stand (0.1 km)",
    nearestRail: "Thiruvananthapuram Central Railway Station (1.3 km)"
  },
  {
    id: 15,
    name: "Thiruvarppu Krishna Temple",
    deity: "Lord Krishna",
    district: "Kottayam",
    location: "Thiruvarppu, Kottayam",
    lat: 9.5788, lng: 76.5336,
    timing: "5:00 AM – 12:00 PM, 5:30 PM – 8:30 PM",
    phone: "+91-481-2412234",
    description: "Ancient Krishna temple on the banks of the Meenachil river. Mentioned in the Bhagavata Purana as one of Lord Krishna's sacred abodes.",
    famous: false,
    tags: ["krishna"],
    dressCode: "Men: Dhoti or mundu. Women: Saree or half-saree. Neat formal wear allowed in outer areas.",
    photography: "Not permitted inside the sanctum.",
    nearestBus: "Thiruvarppu Bus Stop (0.5 km) · Kottayam KSRTC Bus Stand (9 km)",
    nearestRail: "Kottayam Railway Station (9 km)"
  },
  {
    id: 16,
    name: "Kaladi Sree Sharada Temple",
    deity: "Goddess Durga",
    district: "Ernakulam",
    location: "Kaladi, Ernakulam",
    lat: 10.1602, lng: 76.4438,
    timing: "6:00 AM – 1:00 PM, 5:00 PM – 7:30 PM",
    phone: "+91-484-2462345",
    description: "Located at the birthplace of Adi Shankaracharya. A powerful Saraswati and Sharada shrine attracting scholars, students, and devotees from across India.",
    famous: true,
    tags: ["durga", "famous", "heritage"],
    dressCode: "Men: Dhoti or neat formals. Women: Saree or churidar. Shorts and sleeveless not allowed.",
    photography: "Allowed at the Adi Shankaracharya birthplace outside. Restricted inside temples.",
    nearestBus: "Kaladi Bus Stand (0.3 km) · Perumbavoor Bus Stand (10 km)",
    nearestRail: "Aluva Railway Station (14 km)"
  },
  {
    id: 17,
    name: "Jatayu Earth's Center",
    deity: "Lord Rama",
    district: "Kollam",
    location: "Chadayamangalam, Kollam",
    lat: 8.9380, lng: 76.8232,
    timing: "9:00 AM – 6:00 PM (Tue–Sun, closed Monday)",
    phone: "+91-474-2556789",
    description: "Unique hilltop temple complex featuring the world's largest bird sculpture — Jatayu, the mythical eagle from Ramayana. The 200-foot sculpture houses a museum inside.",
    famous: true,
    tags: ["rama", "famous"],
    dressCode: "No strict dress code; decent clothing expected. Comfortable footwear advised for hilly terrain.",
    photography: "Photography freely allowed throughout the complex. Drone photography requires special permission.",
    nearestBus: "Chadayamangalam Bus Stand (5 km)",
    nearestRail: "Mukhathala Railway Station (7 km) · Kollam Railway Station (54 km)"
  },
  {
    id: 18,
    name: "Thali Siva Temple",
    deity: "Lord Shiva",
    district: "Kozhikode",
    location: "Kozhikode Town",
    lat: 11.2602, lng: 75.7804,
    timing: "5:00 AM – 12:00 PM, 5:00 PM – 8:00 PM",
    phone: "+91-495-2721234",
    description: "13th century temple built by the Zamorins of Kozhikode. A rare blend of Malabar and traditional Kerala temple architecture with intricate woodwork.",
    famous: true,
    tags: ["shiva", "famous", "heritage"],
    dressCode: "Men: Dhoti or mundu. Women: Saree or churidar with dupatta. Modest dress strictly enforced.",
    photography: "Permitted in outer courtyard. Not permitted inside sanctum.",
    nearestBus: "Kozhikode KSRTC Bus Stand (1 km) · Palayam Bus Stand (0.6 km)",
    nearestRail: "Kozhikode Railway Station (2 km)"
  },
  {
    id: 19,
    name: "Mangaladevi Temple",
    deity: "Goddess Bhagavathi",
    district: "Idukki",
    location: "Kumily, Idukki",
    lat: 9.5643, lng: 77.1692,
    timing: "Open only on Chithra Pournami (April–May full moon night)",
    phone: "+91-4869-222456",
    description: "Remote forest temple in the Periyar Tiger Reserve at 1337 m elevation. Open to public only once a year on Chithra Pournami night. Surrounded by dense Cardamom Hills forests.",
    famous: true,
    tags: ["bhagavathi", "famous"],
    dressCode: "Traditional dress required on Chithra Pournami. Warm clothing advised due to altitude and night temperatures.",
    photography: "Restricted — forest reserve rules apply. Wildlife photography requires Forest Department permit.",
    nearestBus: "Kumily Bus Stand (15 km)",
    nearestRail: "Kottayam Railway Station (114 km)"
  },
  {
    id: 20,
    name: "Thiruvambady Sri Krishna Temple",
    deity: "Lord Krishna",
    district: "Thrissur",
    location: "Thiruvambady, Thrissur",
    lat: 10.5176, lng: 76.2155,
    timing: "4:00 AM – 11:00 AM, 5:00 PM – 8:30 PM",
    phone: "+91-487-2421111",
    description: "One of the two primary temples of the spectacular Thrissur Pooram festival. The elephant procession from this temple is world-famous.",
    famous: true,
    tags: ["krishna", "famous"],
    dressCode: "Men: Dhoti. Women: Saree or half-saree. Western dress not permitted inside.",
    photography: "Not permitted inside. Festival photography allowed on Pooram day.",
    nearestBus: "Thrissur KSRTC Bus Stand (0.6 km)",
    nearestRail: "Thrissur Railway Station (1.3 km)"
  },
  {
    id: 21,
    name: "Haripad Subramanya Temple",
    deity: "Lord Subramanya",
    district: "Alappuzha",
    location: "Haripad, Alappuzha",
    lat: 9.2832, lng: 76.4671,
    timing: "5:30 AM – 12:00 PM, 5:30 PM – 8:00 PM",
    phone: "+91-479-2412567",
    description: "Famous Subramanya temple in Alappuzha. The annual Ashtami festival draws thousands of devotees. The ten-day Subramanya Ashtami is the most important festival.",
    famous: false,
    tags: ["subramanya"],
    dressCode: "Men: Dhoti or mundu. Women: Saree or churidar. Neat formal dress acceptable.",
    photography: "Allowed in outer precincts only.",
    nearestBus: "Haripad Bus Stand (0.5 km)",
    nearestRail: "Haripad Railway Station (1 km)"
  },
  {
    id: 22,
    name: "Payyannur Subramanya Temple",
    deity: "Lord Subramanya",
    district: "Kannur",
    location: "Payyannur, Kannur",
    lat: 12.0978, lng: 75.2044,
    timing: "5:30 AM – 12:30 PM, 5:30 PM – 8:00 PM",
    phone: "+91-497-7812345",
    description: "Important Subramanya temple in North Kerala famous for the Vela — a brilliant display of fireworks and colourful floats during the annual festival.",
    famous: false,
    tags: ["subramanya"],
    dressCode: "Men: Dhoti or neat trousers. Women: Saree or churidar. Decent attire required.",
    photography: "Permitted outside temple. Restricted inside sanctum.",
    nearestBus: "Payyannur Bus Stand (0.5 km)",
    nearestRail: "Payyannur Railway Station (2 km)"
  },
  {
    id: 23,
    name: "Chettikulangara Bhagavathy Temple",
    deity: "Goddess Bhagavathi",
    district: "Kollam",
    location: "Chettikulangara, Kollam",
    lat: 9.1558, lng: 76.5856,
    timing: "4:30 AM – 12:00 PM, 5:00 PM – 8:00 PM",
    phone: "+91-474-2557234",
    description: "Powerful Bhagavathi temple. The Chettikulangara Bharani is among the grandest festivals in South Kerala, famous for the illuminated kuthira (horse) procession.",
    famous: true,
    tags: ["bhagavathi", "famous"],
    dressCode: "Men: Dhoti or trousers with shirt. Women: Saree or churidar. Modest dress mandatory.",
    photography: "Allowed in outer precincts. Not allowed near sanctum.",
    nearestBus: "Chettikulangara Bus Stop (0.2 km) · Kollam KSRTC Bus Stand (8 km)",
    nearestRail: "Kollam Railway Station (8 km)"
  },
  {
    id: 24,
    name: "Madayipara Bhagavathy Temple",
    deity: "Goddess Bhagavathi",
    district: "Kannur",
    location: "Madayi, Kannur",
    lat: 11.9467, lng: 75.3394,
    timing: "6:00 AM – 12:00 PM, 5:30 PM – 7:30 PM",
    phone: "+91-497-2882345",
    description: "Ancient Bhagavathy temple atop a laterite plateau overlooking the Mahe river estuary. Famous for Theyyam performances — the living god tradition of North Kerala.",
    famous: false,
    tags: ["bhagavathi"],
    dressCode: "Men: Dhoti or neat clothing. Women: Saree or churidar. Traditional dress preferred during festivals.",
    photography: "Permitted. Theyyam photography allowed with respect for performers.",
    nearestBus: "Payyanur Bus Stand (8 km) · Ezhimala Bus Stop (5 km)",
    nearestRail: "Payyanur Railway Station (9 km)"
  },
  {
    id: 25,
    name: "Lokanarkavu Bhagavathy Temple",
    deity: "Goddess Bhagavathi",
    district: "Kozhikode",
    location: "Moozhikkal, Kozhikode",
    lat: 11.3424, lng: 75.8521,
    timing: "5:00 AM – 12:30 PM, 5:30 PM – 8:00 PM",
    phone: "+91-495-2234567",
    description: "One of the powerful Bhagavathi temples in the Malabar region. Known for the annual Pooram Mahotsavam and traditional Thoyyam performances.",
    famous: false,
    tags: ["bhagavathi"],
    dressCode: "Men: Dhoti or trousers. Women: Saree or churidar. Modest dress expected.",
    photography: "Permitted during festival season. Restricted inside shrine.",
    nearestBus: "Moozhikkal Bus Stop (0.3 km) · Kozhikode KSRTC Bus Stand (10 km)",
    nearestRail: "Kozhikode Railway Station (11 km)"
  },
  {
    id: 26,
    name: "Vadakkencherry Mahavishnu Temple",
    deity: "Lord Vishnu",
    district: "Palakkad",
    location: "Vadakkencherry, Palakkad",
    lat: 10.5968, lng: 76.5622,
    timing: "5:00 AM – 12:00 PM, 5:30 PM – 8:00 PM",
    phone: "+91-492-2334567",
    description: "Prominent Vishnu temple in the Palakkad region. The Vaikunta Ekadasi festival attracts thousands of devotees from across Kerala.",
    famous: false,
    tags: ["vishnu"],
    dressCode: "Men: Dhoti or neat formals. Women: Saree or churidar. Traditional dress preferred.",
    photography: "Allowed in outer courtyard. Not permitted near sanctum.",
    nearestBus: "Vadakkencherry Bus Stand (0.5 km) · Palakkad KSRTC Bus Stand (20 km)",
    nearestRail: "Palakkad Railway Station (22 km)"
  },
  {
    id: 27,
    name: "Sasthamkotta Sree Sasta Temple",
    deity: "Lord Ayyappa",
    district: "Kollam",
    location: "Sasthamkotta, Kollam",
    lat: 9.0248, lng: 76.6129,
    timing: "5:30 AM – 12:00 PM, 5:00 PM – 7:30 PM",
    phone: "+91-476-2831234",
    description: "Ancient Sasta temple on the banks of Sasthamkotta Lake — Kerala's largest freshwater lake. A spiritually powerful environment combining nature and devotion.",
    famous: false,
    tags: ["ayyappa"],
    dressCode: "Men: Dhoti or mundu. Women: Saree or churidar. Pilgrimage dress for Sabarimala season devotees.",
    photography: "Permitted at the lakeside and outer areas. Restricted inside sanctum.",
    nearestBus: "Sasthamkotta Bus Stand (0.5 km) · Kollam KSRTC Bus Stand (30 km)",
    nearestRail: "Kundara Railway Station (15 km)"
  },
  {
    id: 28,
    name: "Kaladi Sree Sharada Temple",
    deity: "Goddess Durga",
    district: "Ernakulam",
    location: "Kaladi, Ernakulam",
    lat: 10.1602, lng: 76.4438,
    timing: "6:00 AM – 1:00 PM, 5:00 PM – 7:30 PM",
    phone: "+91-484-2462345",
    description: "Located at the birthplace of Adi Shankaracharya. A powerful Sharada shrine attracting scholars and students. One of four Shankaracharya maths in India.",
    famous: true,
    tags: ["durga", "famous", "heritage"],
    dressCode: "Men: Dhoti or neat formals. Women: Saree or churidar. Shorts and sleeveless not allowed.",
    photography: "Allowed at the Adi Shankaracharya birthplace outside. Restricted inside temples.",
    nearestBus: "Kaladi Bus Stand (0.3 km) · Perumbavoor Bus Stand (10 km)",
    nearestRail: "Aluva Railway Station (14 km)"
  },
];

// Deity colour map for map markers
const DEITY_COLORS = {
  "Lord Vishnu":        "#1565C0",
  "Lord Shiva":         "#6A1B9A",
  "Lord Krishna":       "#1B5E20",
  "Lord Ayyappa":       "#BF360C",
  "Goddess Bhagavathi": "#880E4F",
  "Goddess Durga":      "#E65100",
  "Lord Subramanya":    "#F57F17",
  "Lord Ganesha":       "#4E342E",
  "Lord Rama":          "#006064",
  "Lord Nagaraja":      "#1A237E",
};

const ALL_DISTRICTS = [...new Set(TEMPLES.map(t => t.district))].sort();
const ALL_DEITIES   = [...new Set(TEMPLES.map(t => t.deity))].sort();
